### ISSUE TITLE
scale to more than 3 compute nodes?

### ISSUE THREAD

**Issue by puzzledvacuum** [julenl/BOMSI#1]
Hi, this project is awesome. I can set up 3 compute nodes but I need more, is it possible for example, to scale up to five compute nodes?

**Comment by dguitarbite** [comment]
If you could scale to 3 compute nodes, you should easily be able to scale to 5. @julenl Any pointers here?

**Comment by julenl** [comment]
In principle, it should be possible to create extra compute nodes right from the boot menu. In the older versions there are up to 3 compute nodes, but you you can easily add more by copy/pasting lines from the boot menu and adding more with different names and IPs (compute4, 10.0.0.34, ...).
If you are still interested, let me know, and I'll try to make sure it works in the newest version.

**Comment by dguitarbite** [comment]
Hi Julen,

May be you could add this as a feature in trainig-labs. This would
certainly be an awesome addition.

Regards,
Pranav

**Comment by julenl** [comment]
It is quite trivial... just generate the compute node again but feed it with a new IP and hostname variables. I could take a look into that.
